name: CI/ CD Steps

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        


  deploy:
      runs-on: ubuntu-latest
      if: success() 
      steps:
      - uses: actions/checkout@v3
      - name: Deploying to private server
        uses: appleboy/ssh-action@master # An action made to control Linux servers
        with: 
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd Programmierprojekt # we move into our app's folder
            git pull # we pull any changes from git
            git checkout CICD #only as long as this is not pushed to master
            pip install -r requirements.txt 
            cd website
            pm2 delete main # we reload the app 
            pm2 start main.py --interpreter=python3
